// app/layout.tsx
import { Inter } from 'next/font/google';
import React from 'react';
import ClientLayout from './ClientLayout';

const inter = Inter({ subsets: ['latin'] });

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

interface RootLayoutProps {
  children: React.ReactNode;
}

export default function RootLayout({ children }: RootLayoutProps) {
  return (
    <html lang="en">

      <body className={inter.className}>
      <ClientLayout>
        {children}
      </ClientLayout>
      </body>
    </html>
  );
}


/* import { Inter } from "next/font/google";
 import MainLayout from "../components/MainLayout";
 import Layout from "../components/Layout";
import React from "react";
const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

interface LayoutProps {
  children: React.ReactNode;
 
}


export default function RootLayout({ children }: LayoutProps ) {
  return (
    <html lang="en">
      <body className={inter.className}>{children}</body>
    </html>
  );
}
 */
/*

import React from 'react';
import App from 'next/app';
 
import Layout from '../components/Layout';
import MainLayout from '../components/MainLayout';
class MyApp extends App {
  render() {
    const { Component, pageProps } = this.props;

    const AppLayout = Component.Layout || Layout;
    console.log("COMP", Component.Layout)
    return (
      <MainLayout>
        <AppLayout>
          <Component {...pageProps} />
        </AppLayout>
      </MainLayout>
    );
  }
}

export default MyApp;
*/