// app/layout.tsx
import { Inter } from 'next/font/google';
import React from 'react';
import ClientLayout from './ClientLayout';

const inter = Inter({ subsets: ['latin'] });

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

interface RootLayoutProps {
  children: React.ReactNode;
}

export default function RootLayout({ children }: RootLayoutProps) {
  return (
    <html lang="en">

      <body className={inter.className}>
      <ClientLayout>
        {children}
      </ClientLayout>
      </body>
    </html>
  );
}

/*
import { Inter } from 'next/font/google';
import React from 'react';
import ClientLayout from './ClientLayout';

const inter = Inter({ subsets: ['latin'] });

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

interface RootLayoutProps {
  children: React.ReactNode;
}

export default function RootLayout({ children }: RootLayoutProps) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <ClientLayout>
          {children}
        </ClientLayout>
      </body>
    </html>
  );
}
*/

/*
// app/layout.tsx
import { Inter } from 'next/font/google';
import React from 'react';
import ClientLayout from './ClientLayout';

const inter = Inter({ subsets: ['latin'] });

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

interface RootLayoutProps {
  children: React.ReactNode;
}

export default function RootLayout({ children }: RootLayoutProps) {
  return (
    <html lang="en">

      <body className={inter.className}>
      <ClientLayout>
        {children}
      </ClientLayout>
      </body>
    </html>
  );
}
*/