#!/bin/sh
. "$(dirname "$0")/_/husky.sh"

 
TEST_RESULT=$(npm run test)

 
echo "$TEST_RESULT"

 
if echo "$TEST_RESULT" | grep -q "Test Suites Failed" 
  echo "Tests failed, but pushing anyway..."
  exit 0  
fi

 
exit 0
